services:
  kv:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data:z
    environment:
      DATABASE_URL: sqlite:///app/data/kv.db
      PORT: "3000"
      ENV: DEVELOPMENT
