services:
  kv:
    image: ghcr.io/kukaraf/kv_manager:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./db-data:/app/data
    environment:
      DATABASE_URL: /app/data/kv.db
      PORT: "3000"
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.66:3100/loki/api/v1/push"
        loki-external-labels: "job=kv_manager,env=prod"
